services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://admin:pass@mongo:27017/unicode
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=unicode
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app_network
    healthcheck:
      test: "mongo --eval 'db.runCommand({ ping: 1 })' mongo:27017"
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: kollsh
      ME_CONFIG_MONGODB_ADMINPASSWORD: thisispassword
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
