FROM node:20.13.1-slim

WORKDIR /usr/src/app

# Install necessary build tools and curl for healthcheck
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY package.json yarn.lock ./

# Install all dependencies
RUN yarn install

COPY . .

EXPOSE 5000

CMD ["yarn", "run", "dev"]